name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

# Minimal perms for each action. Adjust if you later add steps that need more.
permissions:
  contents: write # needed to push to gh-pages branch
  pages: write # some pages actions use this
  id-token: write # safe default for pages OIDC
  packages: write # needed to publish to GitHub Packages

jobs:
  publish:
    name: Build, Test, Deploy Storybook, Publish Package
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (install & cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          install_command: npm ci
          build_command: npm run storybook:build
          path: storybook-static
        env:
          # This action expects GH_TOKEN as "username:token"
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm run build

      # Re-configure Node auth just for publish to GH Packages
      - name: Setup Node for GitHub Packages publish
        if: github.event_name == 'release'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          scope: "@ridley"
          registry-url: "https://npm.pkg.github.com"

      - name: Publish to GitHub Packages
        if: github.event_name == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --access=restricted
